Capstone completed
malikhaiderkhan/Capstone-Module-1 pull request #1
Opened 2023-05-31 21:01 UTC by malikhaiderkhan

I complete all the requirements of capstone project. We have to make a website like the template but we are allow to change images and add some changes in the our template.

2023-05-31 23:17 UTC, OLIPLICHE requested changes
Hi @malikhaiderkhan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Build Home and About pages 👍 
- The Web pages are deployed 👍 
- Everything is working fine 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 23:17 UTC, OLIPLICHE commented on about.html
> +         </div>
- Hi, please make sure all the images contain `alt` attributes. because the required `alt` attribute specifies an alternate text for an image if the image cannot be displayed.
- I will advise you to apply the same to the index file.

2023-06-01 10:28 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @malikhaiderkhan ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed GitHub Flow ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 11:02 UTC, merged

2023-06-06 07:12 UTC, RileyManda reviewed
 ———Status Approved:——————————————  > # Status: Approved 🟢 🟢 🟢
> Hi @malikhaiderkhan ,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it: ship it: Congratulations! 🎉
> 
> ## Highlights:
> ✅ You used Gitflow correctly 👍🏽 ✅ The Linter checks passed successfully 👍🏽 ✅ Email field is validated as expected and the form is submitted successfully 👍🏽
> 
> Cheers, and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._